@startuml
actor "Пользователь" as User
boundary "Форма авторизации" as loginForm
control "Модуль авторизации" as loginModul
database "База данных" as DB

User -> loginForm ++ : Ввести данные (логин, пароль)
loginForm -> loginModul ++ : Передать данные (логин, пароль)
loginModul -> DB ++ : Получить данные пользователя (логин)

loginModul <-- DB -- : Данные пользователя

loginModul -> loginModul : Проверить данные пользователя

alt Логин, пароль верны
    loginForm <-- loginModul : JWT токен
    
    loginForm -> loginForm : сохранить JWT
    User <-- loginForm --: Вход выполнен

else Данные не валидны
    
    loginForm <-- loginModul --: ErrorMessage
    
    activate loginForm
    User <-- loginForm : Сообщение о ошибке
    deactivate loginForm
end

@enduml