@startuml
actor "Administrator" as User
boundary "Страница ввода модели" as Page
control "Models" as Models
database "База данных" as DB

User -> Page ++ : Кнопка добавить модель

User <-- Page : Форма добавления модели
User -> Page : Ввести данные модели

Page-> Models ++ : Создать модель

Models-> Models : Validate()

alt validate ok
 
    Models-> DB ++: Сохранить модель

    Models <-- DB -- : Обновленный список

    Page <-- Models : Список моделей
    
    User <-- Page  : Обновленый список моделей


else validate not ok
    
    Page <- Models -- : ErrorMessage
    User <-- Page -- : Вывод сообщения об ошибке

end





@enduml