<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Sun, 27 Mar 2022 17:59:28 +0000
 */
$conf['title'] = 'ARAS';
$conf['lang'] = 'ru';
$conf['license'] = 'publicdomain';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
