# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Sun, 27 Mar 2022 17:59:28 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

sid:$2y$10$f99aDUFFkHHkHxj0YSkpwO7D83e/eJjUjWrPv.b8NhhN9gE8wFWka:Денис:gtcoda@gmail.com:admin,user
